"""Initial tables

Revision ID: 922bd30b9b78
Revises: 
Create Date: 2025-12-07 15:13:05.230530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922bd30b9b78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_categories_id'), 'tech_categories', ['id'], unique=False)
    op.create_index(op.f('ix_tech_categories_name'), 'tech_categories', ['name'], unique=True)
    op.create_table('tech_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('specs', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tech_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_products_id'), 'tech_products', ['id'], unique=False)
    op.create_index(op.f('ix_tech_products_name'), 'tech_products', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['tech_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_tech_products_name'), table_name='tech_products')
    op.drop_index(op.f('ix_tech_products_id'), table_name='tech_products')
    op.drop_table('tech_products')
    op.drop_index(op.f('ix_tech_categories_name'), table_name='tech_categories')
    op.drop_index(op.f('ix_tech_categories_id'), table_name='tech_categories')
    op.drop_table('tech_categories')
    # ### end Alembic commands ###
